# Sample configuration for the Spark processor
source:
  file_path: "data/source/employees.csv"
  delimiter: ","
  header: true
  file_format: "csv"

target:
  type: "sqlite"
  database: "data/employees.db"
  table: "employees"
  mode: "overwrite"  # or append, ignore, error