# Data processor configuration
source:
  file_path: "data/source/employees_large.csv"  # Large dataset for performance testing
  delimiter: ","
  header: true
  file_format: "csv"

target:
  type: "sqlite"
  database: "data/employees.db"
  table: "employees"
  mode: "overwrite"  # or append, ignore, error